cleaning up infrastructure

diff --git a/misc/run-twolink-test b/misc/run-twolink-test
--- a/misc/run-twolink-test
+++ b/misc/run-twolink-test
@@ -1,6 +1,37 @@
-#!/bin/bash
+#! /usr/bin/env bash
 
 # Connects nodes in two namespaces by two links with different bandwidth (10mbit and 100mbit)
+#
+# Optional args:
+#   misc/run-twolink-test [node1.conf] [node2.conf]
+# If provided, configs are used with a forced AdminListen per node.
+
+set -e
+
+conf1="${1:-}"
+conf2="${2:-}"
+tmpconf1=""
+tmpconf2=""
+
+make_config() {
+  local src="$1"
+  local admin="$2"
+  local dst="$3"
+
+  if [ -z "$src" ]; then
+    printf '{AdminListen: "%s"}\n' "$admin" > "$dst"
+    return
+  fi
+
+  if [ ! -f "$src" ]; then
+    echo "Config not found: $src" >&2
+    exit 1
+  fi
+
+  hjson-cli -j "$src" \
+    | jq --arg admin "$admin" '.AdminListen = $admin' \
+    | hjson-cli > "$dst"
+}
 
 ip netns add node1
 ip netns add node2
@@ -19,12 +50,19 @@ ip netns exec node2 tc qdisc add dev veth21 root tbf rate 10mbit burst 8192 late
 ip netns exec node1 tc qdisc add dev veth12 root tbf rate 100mbit burst 8192 latency 1ms
 ip netns exec node2 tc qdisc add dev veth22 root tbf rate 100mbit burst 8192 latency 1ms
 
-echo '{AdminListen: "unix://node1.sock"}' | ip netns exec node1 env PPROFLISTEN=localhost:6060 ./yggdrasil -logging "info,warn,error,debug" -useconf &> node1.log &
-echo '{AdminListen: "unix://node2.sock"}' | ip netns exec node2 env PPROFLISTEN=localhost:6060 ./yggdrasil -logging "info,warn,error,debug" -useconf &> node2.log &
+tmpconf1="$(mktemp)"
+tmpconf2="$(mktemp)"
+make_config "$conf1" "unix://node1.sock" "$tmpconf1"
+make_config "$conf2" "unix://node2.sock" "$tmpconf2"
+
+ip netns exec node1 env PPROFLISTEN=localhost:6060 ./yggdrasil -logging "info,warn,error,debug" -useconffile "$tmpconf1" &> node1.log &
+ip netns exec node2 env PPROFLISTEN=localhost:6060 ./yggdrasil -logging "info,warn,error,debug" -useconffile "$tmpconf2" &> node2.log &
 
 echo "Started, to continue you should (possibly w/ sudo):"
 echo "kill" $(jobs -p)
 wait
+
+rm -f "$tmpconf1" "$tmpconf2"
 
 ip netns delete node1
 ip netns delete node2
